remote_theme: mmistakes/minimal-mistakes
title: Fontys-Intersect
plugins:
  - jekyll-include-cache

include: ["_pages"]

defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single

minimal_mistakes_skin: "neon"
